weights: ./runs/train/exp44/weights/last.pt
cfg: ''
data: data/car.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 400
batch_size: 32
imgsz: 320
rect: false
resume: true
nosave: false
noval: false
noautoanchor: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/train
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
nohalf: false
quantize: false
BackendType: Tensorrt
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
sparse: false
sparse_rate: 0.001
save_dir: runs/train/exp44
